// flow-typed signature: 120a966f3b3505fcd147a13da3038a58
// flow-typed version: <<STUB>>/cross-spawn-promise_v^0.10.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-spawn-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cross-spawn-promise" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cross-spawn-promise/lib/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "cross-spawn-promise/index" {
  declare module.exports: $Exports<"cross-spawn-promise">;
}
declare module "cross-spawn-promise/index.js" {
  declare module.exports: $Exports<"cross-spawn-promise">;
}
declare module "cross-spawn-promise/lib/index.js" {
  declare module.exports: $Exports<"cross-spawn-promise/lib/index">;
}
