// flow-typed signature: 30ac67f21e2f664fa1202ffc5d255abb
// flow-typed version: <<STUB>>/download-git-repo_v^1.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'download-git-repo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "download-git-repo" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "download-git-repo/test/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "download-git-repo/index" {
  declare module.exports: $Exports<"download-git-repo">;
}
declare module "download-git-repo/index.js" {
  declare module.exports: $Exports<"download-git-repo">;
}
declare module "download-git-repo/test/index.js" {
  declare module.exports: $Exports<"download-git-repo/test/index">;
}
