// flow-typed signature: 5ff5c37e3006fa0f30a85ca2fefda16b
// flow-typed version: <<STUB>>/fs.promised_v^3.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs.promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs.promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs.promised/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs.promised/index' {
  declare module.exports: $Exports<'fs.promised'>;
}
declare module 'fs.promised/index.js' {
  declare module.exports: $Exports<'fs.promised'>;
}
declare module 'fs.promised/promisify.js' {
  declare module.exports: $Exports<'fs.promised/promisify'>;
}
