// flow-typed signature: 65dafdd3a74981005b90f1c3a53a727f
// flow-typed version: <<STUB>>/lint-staged_v^9.2.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint-staged' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lint-staged/src/execGit' {
  declare module.exports: any;
}

declare module 'lint-staged/src/generateTasks' {
  declare module.exports: any;
}

declare module 'lint-staged/src/getStagedFiles' {
  declare module.exports: any;
}

declare module 'lint-staged/src/gitWorkflow' {
  declare module.exports: any;
}

declare module 'lint-staged/src/index' {
  declare module.exports: any;
}

declare module 'lint-staged/src/makeCmdTasks' {
  declare module.exports: any;
}

declare module 'lint-staged/src/printErrors' {
  declare module.exports: any;
}

declare module 'lint-staged/src/resolveGitDir' {
  declare module.exports: any;
}

declare module 'lint-staged/src/resolveTaskFn' {
  declare module.exports: any;
}

declare module 'lint-staged/src/runAll' {
  declare module.exports: any;
}

declare module 'lint-staged/src/validateConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lint-staged/src/execGit.js' {
  declare module.exports: $Exports<'lint-staged/src/execGit'>;
}
declare module 'lint-staged/src/generateTasks.js' {
  declare module.exports: $Exports<'lint-staged/src/generateTasks'>;
}
declare module 'lint-staged/src/getStagedFiles.js' {
  declare module.exports: $Exports<'lint-staged/src/getStagedFiles'>;
}
declare module 'lint-staged/src/gitWorkflow.js' {
  declare module.exports: $Exports<'lint-staged/src/gitWorkflow'>;
}
declare module 'lint-staged/src/index.js' {
  declare module.exports: $Exports<'lint-staged/src/index'>;
}
declare module 'lint-staged/src/makeCmdTasks.js' {
  declare module.exports: $Exports<'lint-staged/src/makeCmdTasks'>;
}
declare module 'lint-staged/src/printErrors.js' {
  declare module.exports: $Exports<'lint-staged/src/printErrors'>;
}
declare module 'lint-staged/src/resolveGitDir.js' {
  declare module.exports: $Exports<'lint-staged/src/resolveGitDir'>;
}
declare module 'lint-staged/src/resolveTaskFn.js' {
  declare module.exports: $Exports<'lint-staged/src/resolveTaskFn'>;
}
declare module 'lint-staged/src/runAll.js' {
  declare module.exports: $Exports<'lint-staged/src/runAll'>;
}
declare module 'lint-staged/src/validateConfig.js' {
  declare module.exports: $Exports<'lint-staged/src/validateConfig'>;
}
