// flow-typed signature: 235d95c3daac92a8e82c25a1636adfd8
// flow-typed version: <<STUB>>/pkg-dir_v^4.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pkg-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pkg-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pkg-dir/index' {
  declare module.exports: $Exports<'pkg-dir'>;
}
declare module 'pkg-dir/index.js' {
  declare module.exports: $Exports<'pkg-dir'>;
}
