// flow-typed signature: 08a5933407a641e84ee75cb93b15d07e
// flow-typed version: <<STUB>>/promisify-node_v^0.5.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promisify-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promisify-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promisify-node/test/examples/fn-export' {
  declare module.exports: any;
}

declare module 'promisify-node/test/examples/proto-export' {
  declare module.exports: any;
}

declare module 'promisify-node/test/index' {
  declare module.exports: any;
}

declare module 'promisify-node/utils/args' {
  declare module.exports: any;
}

declare module 'promisify-node/utils/cloneFunction' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promisify-node/index' {
  declare module.exports: $Exports<'promisify-node'>;
}
declare module 'promisify-node/index.js' {
  declare module.exports: $Exports<'promisify-node'>;
}
declare module 'promisify-node/test/examples/fn-export.js' {
  declare module.exports: $Exports<'promisify-node/test/examples/fn-export'>;
}
declare module 'promisify-node/test/examples/proto-export.js' {
  declare module.exports: $Exports<'promisify-node/test/examples/proto-export'>;
}
declare module 'promisify-node/test/index.js' {
  declare module.exports: $Exports<'promisify-node/test/index'>;
}
declare module 'promisify-node/utils/args.js' {
  declare module.exports: $Exports<'promisify-node/utils/args'>;
}
declare module 'promisify-node/utils/cloneFunction.js' {
  declare module.exports: $Exports<'promisify-node/utils/cloneFunction'>;
}
