// flow-typed signature: cd36e47a09cf3545d5b5efab316014dd
// flow-typed version: <<STUB>>/tape-async_v^2.3.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tape-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tape-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tape-async/index' {
  declare module.exports: $Exports<'tape-async'>;
}
declare module 'tape-async/index.js' {
  declare module.exports: $Exports<'tape-async'>;
}
