// flow-typed signature: ce11b64614cabed87659657cf2fe2b3b
// flow-typed version: <<STUB>>/testdouble_v^3.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testdouble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testdouble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testdouble/dist/testdouble' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/adder' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/calculator' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/multiplier' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/subtractor' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/vehicle' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/test/helper' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/test/lib/calculator-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/application' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/files' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/lineman' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/server' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/Gruntfile' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/spec/helpers/helper' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/spec/math-problem-spec' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/vendor/js/underscore' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/accelerometer' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/brake' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/car' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/elastic-thing' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/gas-pedal' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/numbers-only' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/test/helper' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/test/lib/car-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/test/lib/elastic-thing-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/test/lib/numbers-only-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/webpack/test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/webpack/test/math-problem-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'testdouble/generated/tests' {
  declare module.exports: any;
}

declare module 'testdouble/lib/args-match' {
  declare module.exports: any;
}

declare module 'testdouble/lib/config' {
  declare module.exports: any;
}

declare module 'testdouble/lib/constructor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/explain' {
  declare module.exports: any;
}

declare module 'testdouble/lib/function' {
  declare module.exports: any;
}

declare module 'testdouble/lib/log' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/anything' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/arg-that' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/captor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/contains' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/is-a' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/not' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/callback' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/create' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/is-matcher' {
  declare module.exports: any;
}

declare module 'testdouble/lib/object' {
  declare module.exports: any;
}

declare module 'testdouble/lib/quibble.browser' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/imitate' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/is-constructor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/module.browser' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/module' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/property' {
  declare module.exports: any;
}

declare module 'testdouble/lib/reset' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/calls' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/stubbings' {
  declare module.exports: any;
}

declare module 'testdouble/lib/stringify/anything' {
  declare module.exports: any;
}

declare module 'testdouble/lib/stringify/arguments' {
  declare module.exports: any;
}

declare module 'testdouble/lib/testdouble' {
  declare module.exports: any;
}

declare module 'testdouble/lib/util/copy-properties' {
  declare module.exports: any;
}

declare module 'testdouble/lib/util/get-all-custom-prototypal-function-names' {
  declare module.exports: any;
}

declare module 'testdouble/lib/util/lodash-wrap' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify' {
  declare module.exports: any;
}

declare module 'testdouble/lib/version' {
  declare module.exports: any;
}

declare module 'testdouble/lib/when' {
  declare module.exports: any;
}

declare module 'testdouble/src/args-match' {
  declare module.exports: any;
}

declare module 'testdouble/src/config' {
  declare module.exports: any;
}

declare module 'testdouble/src/constructor' {
  declare module.exports: any;
}

declare module 'testdouble/src/explain' {
  declare module.exports: any;
}

declare module 'testdouble/src/function' {
  declare module.exports: any;
}

declare module 'testdouble/src/log' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/anything' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/arg-that' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/captor' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/contains' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/is-a' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/not' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/callback' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/create' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/is-matcher' {
  declare module.exports: any;
}

declare module 'testdouble/src/object' {
  declare module.exports: any;
}

declare module 'testdouble/src/quibble.browser' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/imitate' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/is-constructor' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/module.browser' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/module' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/property' {
  declare module.exports: any;
}

declare module 'testdouble/src/reset' {
  declare module.exports: any;
}

declare module 'testdouble/src/store/calls' {
  declare module.exports: any;
}

declare module 'testdouble/src/store/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/store/stubbings' {
  declare module.exports: any;
}

declare module 'testdouble/src/stringify/anything' {
  declare module.exports: any;
}

declare module 'testdouble/src/stringify/arguments' {
  declare module.exports: any;
}

declare module 'testdouble/src/testdouble' {
  declare module.exports: any;
}

declare module 'testdouble/src/util/copy-properties' {
  declare module.exports: any;
}

declare module 'testdouble/src/util/get-all-custom-prototypal-function-names' {
  declare module.exports: any;
}

declare module 'testdouble/src/util/lodash-wrap' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify' {
  declare module.exports: any;
}

declare module 'testdouble/src/version' {
  declare module.exports: any;
}

declare module 'testdouble/src/when' {
  declare module.exports: any;
}

declare module 'testdouble/test/browser-helper' {
  declare module.exports: any;
}

declare module 'testdouble/test/fixtures/es6class' {
  declare module.exports: any;
}

declare module 'testdouble/test/fixtures/shift' {
  declare module.exports: any;
}

declare module 'testdouble/test/fixtures/turn' {
  declare module.exports: any;
}

declare module 'testdouble/test/src/config-test' {
  declare module.exports: any;
}

declare module 'testdouble/testem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testdouble/dist/testdouble.js' {
  declare module.exports: $Exports<'testdouble/dist/testdouble'>;
}
declare module 'testdouble/examples/babel/lib/adder.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/adder'>;
}
declare module 'testdouble/examples/babel/lib/calculator.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/calculator'>;
}
declare module 'testdouble/examples/babel/lib/multiplier.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/multiplier'>;
}
declare module 'testdouble/examples/babel/lib/subtractor.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/subtractor'>;
}
declare module 'testdouble/examples/babel/lib/vehicle.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/vehicle'>;
}
declare module 'testdouble/examples/babel/test/helper.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/test/helper'>;
}
declare module 'testdouble/examples/babel/test/lib/calculator-test.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/test/lib/calculator-test'>;
}
declare module 'testdouble/examples/lineman/config/application.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/application'>;
}
declare module 'testdouble/examples/lineman/config/files.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/files'>;
}
declare module 'testdouble/examples/lineman/config/lineman.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/lineman'>;
}
declare module 'testdouble/examples/lineman/config/server.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/server'>;
}
declare module 'testdouble/examples/lineman/Gruntfile.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/Gruntfile'>;
}
declare module 'testdouble/examples/lineman/spec/helpers/helper.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/spec/helpers/helper'>;
}
declare module 'testdouble/examples/lineman/spec/math-problem-spec.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/spec/math-problem-spec'>;
}
declare module 'testdouble/examples/lineman/vendor/js/underscore.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/vendor/js/underscore'>;
}
declare module 'testdouble/examples/node/lib/accelerometer.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/accelerometer'>;
}
declare module 'testdouble/examples/node/lib/brake.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/brake'>;
}
declare module 'testdouble/examples/node/lib/car.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/car'>;
}
declare module 'testdouble/examples/node/lib/elastic-thing.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/elastic-thing'>;
}
declare module 'testdouble/examples/node/lib/gas-pedal.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/gas-pedal'>;
}
declare module 'testdouble/examples/node/lib/numbers-only.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/numbers-only'>;
}
declare module 'testdouble/examples/node/test/helper.js' {
  declare module.exports: $Exports<'testdouble/examples/node/test/helper'>;
}
declare module 'testdouble/examples/node/test/lib/car-test.js' {
  declare module.exports: $Exports<'testdouble/examples/node/test/lib/car-test'>;
}
declare module 'testdouble/examples/node/test/lib/elastic-thing-test.js' {
  declare module.exports: $Exports<'testdouble/examples/node/test/lib/elastic-thing-test'>;
}
declare module 'testdouble/examples/node/test/lib/numbers-only-test.js' {
  declare module.exports: $Exports<'testdouble/examples/node/test/lib/numbers-only-test'>;
}
declare module 'testdouble/examples/webpack/test.js' {
  declare module.exports: $Exports<'testdouble/examples/webpack/test'>;
}
declare module 'testdouble/examples/webpack/test/math-problem-test.js' {
  declare module.exports: $Exports<'testdouble/examples/webpack/test/math-problem-test'>;
}
declare module 'testdouble/examples/webpack/webpack.config.js' {
  declare module.exports: $Exports<'testdouble/examples/webpack/webpack.config'>;
}
declare module 'testdouble/generated/tests.js' {
  declare module.exports: $Exports<'testdouble/generated/tests'>;
}
declare module 'testdouble/lib/args-match.js' {
  declare module.exports: $Exports<'testdouble/lib/args-match'>;
}
declare module 'testdouble/lib/config.js' {
  declare module.exports: $Exports<'testdouble/lib/config'>;
}
declare module 'testdouble/lib/constructor.js' {
  declare module.exports: $Exports<'testdouble/lib/constructor'>;
}
declare module 'testdouble/lib/explain.js' {
  declare module.exports: $Exports<'testdouble/lib/explain'>;
}
declare module 'testdouble/lib/function.js' {
  declare module.exports: $Exports<'testdouble/lib/function'>;
}
declare module 'testdouble/lib/log.js' {
  declare module.exports: $Exports<'testdouble/lib/log'>;
}
declare module 'testdouble/lib/matchers/builtin/anything.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/anything'>;
}
declare module 'testdouble/lib/matchers/builtin/arg-that.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/arg-that'>;
}
declare module 'testdouble/lib/matchers/builtin/captor.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/captor'>;
}
declare module 'testdouble/lib/matchers/builtin/contains.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/contains'>;
}
declare module 'testdouble/lib/matchers/builtin/is-a.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/is-a'>;
}
declare module 'testdouble/lib/matchers/builtin/not.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/not'>;
}
declare module 'testdouble/lib/matchers/callback.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/callback'>;
}
declare module 'testdouble/lib/matchers/create.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/create'>;
}
declare module 'testdouble/lib/matchers/index.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/index'>;
}
declare module 'testdouble/lib/matchers/is-matcher.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/is-matcher'>;
}
declare module 'testdouble/lib/object.js' {
  declare module.exports: $Exports<'testdouble/lib/object'>;
}
declare module 'testdouble/lib/quibble.browser.js' {
  declare module.exports: $Exports<'testdouble/lib/quibble.browser'>;
}
declare module 'testdouble/lib/replace/imitate.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/imitate'>;
}
declare module 'testdouble/lib/replace/index.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/index'>;
}
declare module 'testdouble/lib/replace/is-constructor.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/is-constructor'>;
}
declare module 'testdouble/lib/replace/module.browser.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/module.browser'>;
}
declare module 'testdouble/lib/replace/module.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/module'>;
}
declare module 'testdouble/lib/replace/property.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/property'>;
}
declare module 'testdouble/lib/reset.js' {
  declare module.exports: $Exports<'testdouble/lib/reset'>;
}
declare module 'testdouble/lib/store/calls.js' {
  declare module.exports: $Exports<'testdouble/lib/store/calls'>;
}
declare module 'testdouble/lib/store/index.js' {
  declare module.exports: $Exports<'testdouble/lib/store/index'>;
}
declare module 'testdouble/lib/store/stubbings.js' {
  declare module.exports: $Exports<'testdouble/lib/store/stubbings'>;
}
declare module 'testdouble/lib/stringify/anything.js' {
  declare module.exports: $Exports<'testdouble/lib/stringify/anything'>;
}
declare module 'testdouble/lib/stringify/arguments.js' {
  declare module.exports: $Exports<'testdouble/lib/stringify/arguments'>;
}
declare module 'testdouble/lib/testdouble.js' {
  declare module.exports: $Exports<'testdouble/lib/testdouble'>;
}
declare module 'testdouble/lib/util/copy-properties.js' {
  declare module.exports: $Exports<'testdouble/lib/util/copy-properties'>;
}
declare module 'testdouble/lib/util/get-all-custom-prototypal-function-names.js' {
  declare module.exports: $Exports<'testdouble/lib/util/get-all-custom-prototypal-function-names'>;
}
declare module 'testdouble/lib/util/lodash-wrap.js' {
  declare module.exports: $Exports<'testdouble/lib/util/lodash-wrap'>;
}
declare module 'testdouble/lib/verify.js' {
  declare module.exports: $Exports<'testdouble/lib/verify'>;
}
declare module 'testdouble/lib/version.js' {
  declare module.exports: $Exports<'testdouble/lib/version'>;
}
declare module 'testdouble/lib/when.js' {
  declare module.exports: $Exports<'testdouble/lib/when'>;
}
declare module 'testdouble/src/args-match.js' {
  declare module.exports: $Exports<'testdouble/src/args-match'>;
}
declare module 'testdouble/src/config.js' {
  declare module.exports: $Exports<'testdouble/src/config'>;
}
declare module 'testdouble/src/constructor.js' {
  declare module.exports: $Exports<'testdouble/src/constructor'>;
}
declare module 'testdouble/src/explain.js' {
  declare module.exports: $Exports<'testdouble/src/explain'>;
}
declare module 'testdouble/src/function.js' {
  declare module.exports: $Exports<'testdouble/src/function'>;
}
declare module 'testdouble/src/log.js' {
  declare module.exports: $Exports<'testdouble/src/log'>;
}
declare module 'testdouble/src/matchers/builtin/anything.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/anything'>;
}
declare module 'testdouble/src/matchers/builtin/arg-that.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/arg-that'>;
}
declare module 'testdouble/src/matchers/builtin/captor.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/captor'>;
}
declare module 'testdouble/src/matchers/builtin/contains.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/contains'>;
}
declare module 'testdouble/src/matchers/builtin/is-a.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/is-a'>;
}
declare module 'testdouble/src/matchers/builtin/not.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/not'>;
}
declare module 'testdouble/src/matchers/callback.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/callback'>;
}
declare module 'testdouble/src/matchers/create.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/create'>;
}
declare module 'testdouble/src/matchers/index.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/index'>;
}
declare module 'testdouble/src/matchers/is-matcher.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/is-matcher'>;
}
declare module 'testdouble/src/object.js' {
  declare module.exports: $Exports<'testdouble/src/object'>;
}
declare module 'testdouble/src/quibble.browser.js' {
  declare module.exports: $Exports<'testdouble/src/quibble.browser'>;
}
declare module 'testdouble/src/replace/imitate.js' {
  declare module.exports: $Exports<'testdouble/src/replace/imitate'>;
}
declare module 'testdouble/src/replace/index.js' {
  declare module.exports: $Exports<'testdouble/src/replace/index'>;
}
declare module 'testdouble/src/replace/is-constructor.js' {
  declare module.exports: $Exports<'testdouble/src/replace/is-constructor'>;
}
declare module 'testdouble/src/replace/module.browser.js' {
  declare module.exports: $Exports<'testdouble/src/replace/module.browser'>;
}
declare module 'testdouble/src/replace/module.js' {
  declare module.exports: $Exports<'testdouble/src/replace/module'>;
}
declare module 'testdouble/src/replace/property.js' {
  declare module.exports: $Exports<'testdouble/src/replace/property'>;
}
declare module 'testdouble/src/reset.js' {
  declare module.exports: $Exports<'testdouble/src/reset'>;
}
declare module 'testdouble/src/store/calls.js' {
  declare module.exports: $Exports<'testdouble/src/store/calls'>;
}
declare module 'testdouble/src/store/index.js' {
  declare module.exports: $Exports<'testdouble/src/store/index'>;
}
declare module 'testdouble/src/store/stubbings.js' {
  declare module.exports: $Exports<'testdouble/src/store/stubbings'>;
}
declare module 'testdouble/src/stringify/anything.js' {
  declare module.exports: $Exports<'testdouble/src/stringify/anything'>;
}
declare module 'testdouble/src/stringify/arguments.js' {
  declare module.exports: $Exports<'testdouble/src/stringify/arguments'>;
}
declare module 'testdouble/src/testdouble.js' {
  declare module.exports: $Exports<'testdouble/src/testdouble'>;
}
declare module 'testdouble/src/util/copy-properties.js' {
  declare module.exports: $Exports<'testdouble/src/util/copy-properties'>;
}
declare module 'testdouble/src/util/get-all-custom-prototypal-function-names.js' {
  declare module.exports: $Exports<'testdouble/src/util/get-all-custom-prototypal-function-names'>;
}
declare module 'testdouble/src/util/lodash-wrap.js' {
  declare module.exports: $Exports<'testdouble/src/util/lodash-wrap'>;
}
declare module 'testdouble/src/verify.js' {
  declare module.exports: $Exports<'testdouble/src/verify'>;
}
declare module 'testdouble/src/version.js' {
  declare module.exports: $Exports<'testdouble/src/version'>;
}
declare module 'testdouble/src/when.js' {
  declare module.exports: $Exports<'testdouble/src/when'>;
}
declare module 'testdouble/test/browser-helper.js' {
  declare module.exports: $Exports<'testdouble/test/browser-helper'>;
}
declare module 'testdouble/test/fixtures/es6class.js' {
  declare module.exports: $Exports<'testdouble/test/fixtures/es6class'>;
}
declare module 'testdouble/test/fixtures/shift.js' {
  declare module.exports: $Exports<'testdouble/test/fixtures/shift'>;
}
declare module 'testdouble/test/fixtures/turn.js' {
  declare module.exports: $Exports<'testdouble/test/fixtures/turn'>;
}
declare module 'testdouble/test/src/config-test.js' {
  declare module.exports: $Exports<'testdouble/test/src/config-test'>;
}
declare module 'testdouble/testem.js' {
  declare module.exports: $Exports<'testdouble/testem'>;
}
